# Generated by Django 5.1.4 on 2024-12-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='country',
            field=models.CharField(default='India', max_length=50),
        ),
    ]
